// ============================================================================
//  Moon Bugs — Lunar Defense
//  A modern, macroquad-based homage to Windmill Software's 1983 "Moon Bugs".
//
//  Defend a row of fuel drums on the lunar surface from swooping alien bugs.
//  Bugs descend in weaving patterns, then dive to grab a drum and haul it off
//  the top of the screen. Shoot a carrier and it drops the drum — which falls
//  safely back to the ground if it survives. Survive escalating waves, grab
//  power-ups, and rack up a score.
//
//  Controls:
//    ← / → or A / D ...... move buggy
//    Space / ↑ ........... fire
//    P ................... pause
//    Enter ............... start / restart
//    Esc ................. quit
// ============================================================================

use macroquad::audio::{
    load_sound_from_bytes, play_sound, play_sound_once, set_sound_volume, stop_sound,
    PlaySoundParams, Sound,
};
use macroquad::prelude::*;
use macroquad::rand::{gen_range, srand};

// ---- Audio -----------------------------------------------------------------
// SFX are procedurally generated by `tools/gen_sounds.py` into `assets/` and
// then *embedded into the binary* at compile time via `include_bytes!`, so the
// game ships as a single self-contained executable with no asset folder needed.
// Decoding is best-effort: if anything fails the game simply runs silent.
struct Audio {
    shoot: Sound,
    explosion: Sound,
    hit: Sound,
    powerup: Sound,
    drum_lost: Sound,
    wave: Sound,
    gameover: Sound,
    hurt: Sound,
    music: Sound,
    music_boss: Sound,
}

impl Audio {
    async fn load() -> Option<Audio> {
        Some(Audio {
            shoot: load_sound_from_bytes(include_bytes!("../assets/shoot.wav")).await.ok()?,
            explosion: load_sound_from_bytes(include_bytes!("../assets/explosion.wav")).await.ok()?,
            hit: load_sound_from_bytes(include_bytes!("../assets/hit.wav")).await.ok()?,
            powerup: load_sound_from_bytes(include_bytes!("../assets/powerup.wav")).await.ok()?,
            drum_lost: load_sound_from_bytes(include_bytes!("../assets/drum_lost.wav")).await.ok()?,
            wave: load_sound_from_bytes(include_bytes!("../assets/wave.wav")).await.ok()?,
            gameover: load_sound_from_bytes(include_bytes!("../assets/gameover.wav")).await.ok()?,
            hurt: load_sound_from_bytes(include_bytes!("../assets/hurt.wav")).await.ok()?,
            music: load_sound_from_bytes(include_bytes!("../assets/music.wav")).await.ok()?,
            music_boss: load_sound_from_bytes(include_bytes!("../assets/music_boss.wav")).await.ok()?,
        })
    }
}

const MUSIC_VOL: f32 = 0.35;

// ---- Tunable constants -----------------------------------------------------
const GROUND_H: f32 = 72.0; // height of the lunar surface strip
const PLAYER_W: f32 = 48.0;
const PLAYER_H: f32 = 22.0;
const PLAYER_SPEED: f32 = 400.0;
const BULLET_SPEED: f32 = 640.0;
const GRAVITY: f32 = 540.0;
const NUM_DRUMS: usize = 5;
const START_LIVES: i32 = 3;
const MAX_LIVES: i32 = 5; // extra-life power-ups cap here so hearts fit the HUD
const DRUM_W: f32 = 24.0;
const DRUM_H: f32 = 28.0;
const POWERUP_CHANCE: f32 = 0.16; // chance a killed bug drops a power-up
const POWERUP_DURATION: f32 = 8.0;
const SHIELD_DURATION: f32 = 6.0;

// ---- Layout helpers --------------------------------------------------------
fn ground_y() -> f32 {
    screen_height() - GROUND_H
}
fn player_y() -> f32 {
    ground_y() - PLAYER_H
}

// Draw a heart centered at (cx, cy): two top lobes plus a bottom point.
fn draw_heart(cx: f32, cy: f32, s: f32, color: Color) {
    draw_circle(cx - s * 0.5, cy - s * 0.35, s * 0.6, color);
    draw_circle(cx + s * 0.5, cy - s * 0.35, s * 0.6, color);
    draw_triangle(
        vec2(cx - s * 1.02, cy - s * 0.05),
        vec2(cx + s * 1.02, cy - s * 0.05),
        vec2(cx, cy + s * 1.15),
        color,
    );
}

// ---- Weapons ---------------------------------------------------------------
#[derive(Clone, Copy, PartialEq)]
enum Weapon {
    Normal,
    Rapid,
    Spread,
}

impl Weapon {
    fn cooldown(self) -> f32 {
        match self {
            Weapon::Normal => 0.27,
            Weapon::Rapid => 0.10,
            Weapon::Spread => 0.34,
        }
    }
    fn label(self) -> &'static str {
        match self {
            Weapon::Normal => "STANDARD",
            Weapon::Rapid => "RAPID",
            Weapon::Spread => "SPREAD",
        }
    }
}

// ---- Power-ups -------------------------------------------------------------
#[derive(Clone, Copy, PartialEq)]
enum PowerKind {
    Rapid,
    Spread,
    Shield,
    ExtraLife,
}

impl PowerKind {
    fn color(self) -> Color {
        match self {
            PowerKind::Rapid => Color::new(1.0, 0.85, 0.2, 1.0),
            PowerKind::Spread => Color::new(0.3, 0.9, 1.0, 1.0),
            PowerKind::Shield => Color::new(0.6, 1.0, 0.5, 1.0),
            PowerKind::ExtraLife => Color::new(1.0, 0.4, 0.45, 1.0),
        }
    }
    fn glyph(self) -> &'static str {
        match self {
            PowerKind::Rapid => "R",
            PowerKind::Spread => "S",
            PowerKind::Shield => "+",
            PowerKind::ExtraLife => "", // drawn as a heart instead of text
        }
    }
}

struct PowerUp {
    pos: Vec2,
    vel_y: f32,
    kind: PowerKind,
    spin: f32,
}

// ---- Entities --------------------------------------------------------------
struct Bullet {
    pos: Vec2,
    vel: Vec2,
}

struct Drum {
    pos: Vec2,   // top-left corner
    home_y: f32, // resting y on the ground
    alive: bool, // false = stolen / destroyed
    carried: bool,
    falling: bool,
    vel_y: f32,
    bonked: bool, // already struck the player during the current fall
}

impl Drum {
    fn center(&self) -> Vec2 {
        vec2(self.pos.x + DRUM_W * 0.5, self.pos.y + DRUM_H * 0.5)
    }
    fn targetable(&self) -> bool {
        self.alive && !self.carried
    }
}

#[derive(Clone, Copy, PartialEq)]
enum BugState {
    Descend,
    Dive(usize), // index of targeted drum
    Carry(usize),
    Flee,
}

struct Bug {
    pos: Vec2,
    base_x: f32,
    amp: f32,
    freq: f32,
    phase: f32,
    fall_speed: f32,
    dive_y: f32, // y at which it commits to a dive
    wobble: f32,
    state: BugState,
    hp: i32,
    max_hp: i32, // for the boss health bar
    radius: f32,
    color: Color,
    flap: f32,
    boss: bool,
    hit_cd: f32, // boss: cooldown between contact hits on the player
}

struct Particle {
    pos: Vec2,
    vel: Vec2,
    life: f32,
    max_life: f32,
    color: Color,
    size: f32,
}

struct Star {
    pos: Vec2,
    size: f32,
    twinkle: f32,
    speed: f32,
}

// ---- Game state ------------------------------------------------------------
#[derive(PartialEq)]
enum Phase {
    Menu,
    Playing,
    Paused,
    GameOver,
}

struct Game {
    phase: Phase,
    player_x: f32,
    weapon: Weapon,
    weapon_timer: f32,
    shield_timer: f32,
    cooldown: f32,
    lives: i32,
    score: i32,
    high_score: i32,
    wave: i32,
    bullets: Vec<Bullet>,
    drums: Vec<Drum>,
    bugs: Vec<Bug>,
    particles: Vec<Particle>,
    powerups: Vec<PowerUp>,
    stars: Vec<Star>,
    bugs_to_spawn: i32,
    spawn_timer: f32,
    spawn_interval: f32,
    banner_timer: f32,
    banner_text: String,
    flash_timer: f32,
    time: f32,
    audio: Option<Audio>,
    mute_sfx: bool,
    mute_music: bool,
    boss_music: bool, // which track is currently looping
}

impl Game {
    fn new() -> Self {
        let stars = (0..90)
            .map(|_| Star {
                pos: vec2(gen_range(0.0, 900.0), gen_range(0.0, 640.0)),
                size: gen_range(0.6, 2.2),
                twinkle: gen_range(0.0, 6.28),
                speed: gen_range(0.4, 1.6),
            })
            .collect();
        Game {
            phase: Phase::Menu,
            player_x: 0.0,
            weapon: Weapon::Normal,
            weapon_timer: 0.0,
            shield_timer: 0.0,
            cooldown: 0.0,
            lives: START_LIVES,
            score: 0,
            high_score: 0,
            wave: 0,
            bullets: Vec::new(),
            drums: Vec::new(),
            bugs: Vec::new(),
            particles: Vec::new(),
            powerups: Vec::new(),
            stars,
            bugs_to_spawn: 0,
            spawn_timer: 0.0,
            spawn_interval: 1.2,
            banner_timer: 0.0,
            banner_text: String::new(),
            flash_timer: 0.0,
            time: 0.0,
            audio: None,
            mute_sfx: false,
            mute_music: false,
            boss_music: false,
        }
    }

    // Play a one-shot effect, unless SFX are muted or audio failed to load.
    fn sfx(&self, pick: impl Fn(&Audio) -> &Sound) {
        if self.mute_sfx {
            return;
        }
        if let Some(a) = &self.audio {
            play_sound_once(pick(a));
        }
    }

    fn music_volume(&self) -> f32 {
        if self.mute_music {
            0.0
        } else {
            MUSIC_VOL
        }
    }

    // Start the looping track that matches the current boss_music state.
    fn start_music(&self) {
        if let Some(a) = &self.audio {
            let track = if self.boss_music { &a.music_boss } else { &a.music };
            play_sound(
                track,
                PlaySoundParams {
                    looped: true,
                    volume: self.music_volume(),
                },
            );
        }
    }

    // Cross-fade-free swap between the calm and boss themes.
    fn switch_music(&mut self, boss: bool) {
        if self.boss_music == boss {
            return;
        }
        self.boss_music = boss;
        if let Some(a) = &self.audio {
            stop_sound(&a.music);
            stop_sound(&a.music_boss);
        }
        self.start_music();
    }

    // Flip the music mute and apply it to the active track without restarting it.
    fn toggle_music(&mut self) {
        self.mute_music = !self.mute_music;
        if let Some(a) = &self.audio {
            let track = if self.boss_music { &a.music_boss } else { &a.music };
            set_sound_volume(track, self.music_volume());
        }
    }

    // The two clickable top-right toggle buttons: (sfx, music).
    fn ui_buttons() -> (Rect, Rect) {
        let (w, h, pad, gap, y) = (36.0, 28.0, 10.0, 8.0, 8.0);
        let music = Rect::new(screen_width() - w - pad, y, w, h);
        let sfx = Rect::new(music.x - w - gap, y, w, h);
        (sfx, music)
    }

    // Handle clicks on the audio toggle buttons (works in every phase).
    fn handle_ui_click(&mut self) {
        if !is_mouse_button_pressed(MouseButton::Left) {
            return;
        }
        let (mx, my) = mouse_position();
        let p = vec2(mx, my);
        let (sfx_r, music_r) = Self::ui_buttons();
        if sfx_r.contains(p) {
            self.mute_sfx = !self.mute_sfx;
        } else if music_r.contains(p) {
            self.toggle_music();
        }
    }

    // -- Reset for a fresh run ----------------------------------------------
    fn start(&mut self) {
        self.phase = Phase::Playing;
        self.player_x = screen_width() * 0.5;
        self.weapon = Weapon::Normal;
        self.weapon_timer = 0.0;
        self.shield_timer = 0.0;
        self.cooldown = 0.0;
        self.lives = START_LIVES;
        self.score = 0;
        self.wave = 0;
        self.bullets.clear();
        self.bugs.clear();
        self.particles.clear();
        self.powerups.clear();
        self.spawn_drums();
        self.next_wave();
    }

    fn spawn_drums(&mut self) {
        self.drums.clear();
        let w = screen_width();
        let margin = 90.0;
        let span = w - margin * 2.0;
        let gy = ground_y() - DRUM_H + 6.0;
        for i in 0..NUM_DRUMS {
            let t = if NUM_DRUMS > 1 {
                i as f32 / (NUM_DRUMS - 1) as f32
            } else {
                0.5
            };
            let x = margin + span * t - DRUM_W * 0.5;
            self.drums.push(Drum {
                pos: vec2(x, gy),
                home_y: gy,
                alive: true,
                carried: false,
                falling: false,
                vel_y: 0.0,
                bonked: false,
            });
        }
    }

    fn next_wave(&mut self) {
        self.wave += 1;
        self.spawn_interval = (1.2 - self.wave as f32 * 0.06).max(0.35);
        self.spawn_timer = 0.6;
        if self.wave % 10 == 0 {
            // Boss wave: spawn the boss now plus a small escort. The wave can't
            // clear until the boss is destroyed (it's in self.bugs).
            self.spawn_boss();
            self.bugs_to_spawn = 6;
            self.banner_text = format!("BOSS  —  WAVE {}", self.wave);
            self.banner_timer = 2.4;
        } else {
            self.bugs_to_spawn = 4 + self.wave * 2;
            self.banner_text = format!("WAVE {}", self.wave);
            self.banner_timer = 1.8;
        }
        // Switch to the scary boss theme on boss waves, back to calm otherwise.
        self.switch_music(self.wave % 10 == 0);
        self.sfx(|a| &a.wave);
    }

    fn alive_drums(&self) -> usize {
        self.drums.iter().filter(|d| d.alive).count()
    }

    // -- Spawn a single bug at the top --------------------------------------
    fn spawn_bug(&mut self) {
        let w = screen_width();
        let base_x = gen_range(60.0, w - 60.0);
        // Tougher, slower armored bugs start appearing on later waves.
        let armored = self.wave >= 3 && gen_range(0.0, 1.0) < 0.22;
        let hp = if armored { 2 } else { 1 };
        let color = if armored {
            Color::new(0.95, 0.45, 0.85, 1.0)
        } else {
            let g = gen_range(0.55, 0.95);
            Color::new(0.45, g, 0.55, 1.0)
        };
        let speed_boost = self.wave as f32 * 7.0;
        self.bugs.push(Bug {
            pos: vec2(base_x, -20.0),
            base_x,
            amp: gen_range(28.0, 78.0),
            freq: gen_range(1.4, 2.8),
            phase: gen_range(0.0, 6.28),
            fall_speed: gen_range(55.0, 80.0) + speed_boost,
            dive_y: gen_range(120.0, ground_y() * 0.55),
            wobble: 0.0,
            state: BugState::Descend,
            hp,
            max_hp: hp,
            radius: if armored { 16.0 } else { 13.0 },
            color,
            flap: gen_range(0.0, 6.28),
            boss: false,
            hit_cd: 0.0,
        });
    }

    // -- Spawn the big, high-HP boss (every 10th wave) ----------------------
    fn spawn_boss(&mut self) {
        let w = screen_width();
        let hp = 20 + self.wave; // wave 10 -> 30, wave 20 -> 40, ...
        self.bugs.push(Bug {
            pos: vec2(w * 0.5, -50.0),
            base_x: w * 0.5,
            amp: w * 0.30,
            freq: 0.6,
            phase: 0.0,
            fall_speed: 14.0, // creeps down slowly so the fight has room to play out
            dive_y: 0.0,
            wobble: 0.0,
            state: BugState::Descend,
            hp,
            max_hp: hp,
            radius: 38.0,
            color: Color::new(0.92, 0.2, 0.32, 1.0),
            flap: 0.0,
            boss: true,
            hit_cd: 0.0,
        });
    }

    fn nearest_targetable_drum(&self, from: Vec2) -> Option<usize> {
        let mut best = None;
        let mut best_d = f32::MAX;
        for (i, d) in self.drums.iter().enumerate() {
            if d.targetable() {
                let dist = d.center().distance_squared(from);
                if dist < best_d {
                    best_d = dist;
                    best = Some(i);
                }
            }
        }
        best
    }

    // -- Fire the current weapon --------------------------------------------
    fn fire(&mut self) {
        if self.cooldown > 0.0 {
            return;
        }
        self.cooldown = self.weapon.cooldown();
        let muzzle = vec2(self.player_x, player_y() - 4.0);
        let angles: &[f32] = match self.weapon {
            Weapon::Spread => &[-0.22, 0.0, 0.22],
            _ => &[0.0],
        };
        for &angle in angles {
            self.bullets.push(Bullet {
                pos: muzzle,
                vel: vec2(angle.sin() * BULLET_SPEED, -angle.cos() * BULLET_SPEED),
            });
        }
        self.sfx(|a| &a.shoot);
    }

    fn pickup_powerup(&mut self, kind: PowerKind) {
        match kind {
            PowerKind::Rapid => {
                self.weapon = Weapon::Rapid;
                self.weapon_timer = POWERUP_DURATION;
            }
            PowerKind::Spread => {
                self.weapon = Weapon::Spread;
                self.weapon_timer = POWERUP_DURATION;
            }
            PowerKind::Shield => {
                self.shield_timer = SHIELD_DURATION;
            }
            PowerKind::ExtraLife => {
                self.lives = (self.lives + 1).min(MAX_LIVES);
            }
        }
    }

    fn burst(&mut self, pos: Vec2, color: Color, count: usize, power: f32) {
        for _ in 0..count {
            let a: f32 = gen_range(0.0, 6.2831);
            let s = gen_range(40.0, 40.0 + power);
            let life = gen_range(0.3, 0.7);
            self.particles.push(Particle {
                pos,
                vel: vec2(a.cos() * s, a.sin() * s),
                life,
                max_life: life,
                color,
                size: gen_range(1.5, 3.5),
            });
        }
    }

    fn lose_life(&mut self, at: Vec2) {
        self.lives -= 1;
        self.flash_timer = 0.25;
        self.burst(at, Color::new(1.0, 0.4, 0.3, 1.0), 26, 160.0);
        self.sfx(|a| &a.hurt);
        if self.lives <= 0 {
            self.game_over();
        }
    }

    fn game_over(&mut self) {
        self.phase = Phase::GameOver;
        if self.score > self.high_score {
            self.high_score = self.score;
        }
        self.switch_music(false); // back to the calm theme on the game-over screen
        self.sfx(|a| &a.gameover);
    }

    // -- Main per-frame update ----------------------------------------------
    fn update(&mut self, dt: f32) {
        self.time += dt;
        if self.banner_timer > 0.0 {
            self.banner_timer -= dt;
        }
        if self.flash_timer > 0.0 {
            self.flash_timer -= dt;
        }

        // --- Input: movement ---
        let mut dir = 0.0;
        if is_key_down(KeyCode::Left) || is_key_down(KeyCode::A) {
            dir -= 1.0;
        }
        if is_key_down(KeyCode::Right) || is_key_down(KeyCode::D) {
            dir += 1.0;
        }
        self.player_x += dir * PLAYER_SPEED * dt;
        self.player_x = self
            .player_x
            .clamp(PLAYER_W * 0.5, screen_width() - PLAYER_W * 0.5);

        // --- Input: fire ---
        if self.cooldown > 0.0 {
            self.cooldown -= dt;
        }
        if is_key_down(KeyCode::Space) || is_key_down(KeyCode::Up) {
            self.fire();
        }

        // --- Power-up timers ---
        if self.weapon_timer > 0.0 {
            self.weapon_timer -= dt;
            if self.weapon_timer <= 0.0 {
                self.weapon = Weapon::Normal;
            }
        }
        if self.shield_timer > 0.0 {
            self.shield_timer -= dt;
        }

        // --- Spawn bugs across the wave ---
        if self.bugs_to_spawn > 0 {
            self.spawn_timer -= dt;
            if self.spawn_timer <= 0.0 {
                self.spawn_bug();
                self.bugs_to_spawn -= 1;
                self.spawn_timer = self.spawn_interval;
            }
        } else if self.bugs.is_empty() && self.banner_timer <= 0.0 {
            // Wave cleared — bonus and advance.
            self.score += 100 * self.wave;
            self.next_wave();
        }

        self.update_bullets(dt);
        self.update_bugs(dt);
        self.update_drums(dt);
        self.update_powerups(dt);
        self.update_particles(dt);

        // --- Lose condition: every drum gone ---
        if self.alive_drums() == 0 && self.phase == Phase::Playing {
            self.game_over();
        }
    }

    fn update_bullets(&mut self, dt: f32) {
        for b in &mut self.bullets {
            b.pos += b.vel * dt;
        }
        self.bullets
            .retain(|b| b.pos.y > -10.0 && b.pos.x > -10.0 && b.pos.x < screen_width() + 10.0);
    }

    fn update_bugs(&mut self, dt: f32) {
        let gy = ground_y();
        let py = player_y();
        let mut kills: Vec<(Vec2, Color)> = Vec::new();
        let mut life_hits: Vec<Vec2> = Vec::new();

        // Move the bug list out of `self` so the AI helpers can borrow
        // `self.drums` / `self.bullets` immutably while we mutate the bugs.
        let mut bugs = std::mem::take(&mut self.bugs);

        // Move + state machine.
        for bug in &mut bugs {
            bug.flap += dt * 14.0;

            // The boss has its own behaviour: weave across the top, creep down
            // slowly, and bump the buggy for damage (on a cooldown) rather than
            // diving for drums. It only dies to sustained gunfire.
            if bug.boss {
                bug.wobble += dt;
                bug.pos.x = (bug.base_x + (bug.wobble * bug.freq).sin() * bug.amp)
                    .clamp(bug.radius, screen_width() - bug.radius);
                bug.pos.y += bug.fall_speed * dt;
                if bug.hit_cd > 0.0 {
                    bug.hit_cd -= dt;
                }
                if bug.pos.y + bug.radius >= py
                    && (bug.pos.x - self.player_x).abs() < PLAYER_W * 0.5 + bug.radius
                {
                    if bug.hit_cd <= 0.0 {
                        bug.hit_cd = 1.0;
                        if self.shield_timer > 0.0 {
                            self.burst(bug.pos, bug.color, 18, 150.0);
                        } else {
                            life_hits.push(vec2(self.player_x, py));
                        }
                    }
                    bug.pos.y = py - bug.radius - 30.0; // bounce up, don't sit on the player
                }
                continue;
            }

            match bug.state {
                BugState::Descend => {
                    bug.wobble += dt;
                    bug.pos.y += bug.fall_speed * dt;
                    bug.pos.x = bug.base_x + (bug.wobble * bug.freq + bug.phase).sin() * bug.amp;
                    if bug.pos.y >= bug.dive_y {
                        match self.nearest_targetable_drum(bug.pos) {
                            Some(idx) => bug.state = BugState::Dive(idx),
                            None => bug.state = BugState::Flee,
                        }
                    }
                }
                BugState::Dive(idx) => {
                    if !self.drums[idx].targetable() {
                        // Lost the target — find another or flee.
                        bug.state = match self.nearest_targetable_drum(bug.pos) {
                            Some(n) => BugState::Dive(n),
                            None => BugState::Flee,
                        };
                    } else {
                        let target = self.drums[idx].center();
                        let to = target - bug.pos;
                        let dist = to.length();
                        let dive_speed = 210.0 + self.wave as f32 * 9.0;
                        if dist < 18.0 {
                            self.drums[idx].carried = true;
                            self.drums[idx].falling = false;
                            bug.state = BugState::Carry(idx);
                        } else {
                            bug.pos += to / dist * dive_speed * dt;
                        }
                    }
                }
                BugState::Carry(idx) => {
                    let carry_speed = 130.0 + self.wave as f32 * 6.0;
                    bug.pos.y -= carry_speed * dt;
                    // Drift back toward spawn column while climbing.
                    bug.pos.x += (bug.base_x - bug.pos.x) * 0.6 * dt;
                    self.drums[idx].pos = vec2(bug.pos.x - DRUM_W * 0.5, bug.pos.y + bug.radius);
                    if bug.pos.y < -30.0 {
                        // Drum hauled off the top — it's gone for good.
                        self.drums[idx].alive = false;
                        self.drums[idx].carried = false;
                        bug.hp = 0; // despawn the bug with its loot
                        self.sfx(|a| &a.drum_lost);
                    }
                }
                BugState::Flee => {
                    bug.pos.y -= (120.0 + self.wave as f32 * 6.0) * dt;
                    bug.pos.x =
                        bug.base_x + (bug.wobble * bug.freq + bug.phase).sin() * bug.amp * 0.4;
                }
            }

            // Collision with the player buggy (any low, non-carrying bug).
            if !matches!(bug.state, BugState::Carry(_)) && bug.pos.y + bug.radius >= py {
                if (bug.pos.x - self.player_x).abs() < PLAYER_W * 0.5 + bug.radius * 0.7 {
                    if self.shield_timer > 0.0 {
                        kills.push((bug.pos, bug.color));
                    } else {
                        life_hits.push(bug.pos);
                    }
                    bug.hp = 0;
                }
            }

            // A bug that leaves the playfield (off the bottom, or fleeing off
            // the top) is retired — otherwise a fleeing bug would linger forever
            // above the screen and the wave would never count as cleared.
            if bug.pos.y - bug.radius > gy + 40.0 || bug.pos.y + bug.radius < -60.0 {
                bug.hp = 0;
            }
        }

        // Bullet ↔ bug collisions.
        for bug in &mut bugs {
            if bug.hp <= 0 {
                continue;
            }
            let mut hit_index = None;
            for (bi, bl) in self.bullets.iter().enumerate() {
                if bl.pos.distance(bug.pos) < bug.radius + 4.0 {
                    hit_index = Some(bi);
                    break;
                }
            }
            if let Some(bi) = hit_index {
                self.bullets.swap_remove(bi);
                bug.hp -= 1;
                if bug.hp <= 0 {
                    // If it was carrying a drum, drop it.
                    if let BugState::Carry(idx) = bug.state {
                        self.drums[idx].carried = false;
                        self.drums[idx].falling = true;
                        self.drums[idx].vel_y = 0.0;
                        self.drums[idx].bonked = false;
                    }
                    if bug.boss {
                        // Big payoff: large score, a huge blast, and a
                        // guaranteed extra-life drop.
                        self.score += 500 + self.wave * 40;
                        self.burst(bug.pos, bug.color, 60, 240.0);
                        self.burst(bug.pos, Color::new(1.0, 0.9, 0.5, 1.0), 30, 180.0);
                        self.powerups.push(PowerUp {
                            pos: bug.pos,
                            vel_y: 50.0,
                            kind: PowerKind::ExtraLife,
                            spin: 0.0,
                        });
                        self.flash_timer = 0.25;
                    } else {
                        self.score += 50;
                        kills.push((bug.pos, bug.color));
                    }
                    self.sfx(|a| &a.explosion);
                } else if bug.boss {
                    // Chip damage on the boss — score only, no sound spam.
                    self.score += 5;
                } else {
                    // Glancing hit on an armored bug — small spark.
                    self.score += 10;
                    self.sfx(|a| &a.hit);
                }
            }
        }

        // Resolve kills queued above (explosions + power-up drops).
        for (pos, color) in kills {
            self.burst(pos, color, 16, 130.0);
            if gen_range(0.0, 1.0) < POWERUP_CHANCE {
                // Extra lives are the rare prize (~10% of drops); the rest are
                // evenly split between the three combat power-ups.
                let kind = match gen_range(0, 10) {
                    0..=2 => PowerKind::Rapid,
                    3..=5 => PowerKind::Spread,
                    6..=8 => PowerKind::Shield,
                    _ => PowerKind::ExtraLife,
                };
                self.powerups.push(PowerUp {
                    pos,
                    vel_y: 70.0,
                    kind,
                    spin: 0.0,
                });
            }
        }
        for at in life_hits {
            self.lose_life(at);
        }

        bugs.retain(|b| b.hp > 0);
        self.bugs = bugs;
    }

    fn update_drums(&mut self, dt: f32) {
        let py = player_y();
        let px = self.player_x;
        let shielded = self.shield_timer > 0.0;
        // Player's hit box (matches the buggy's hull + cannon).
        let p_left = px - PLAYER_W * 0.5;
        let p_right = px + PLAYER_W * 0.5;
        let p_top = py - 8.0;
        let p_bottom = py + PLAYER_H;

        let mut life_hits: Vec<Vec2> = Vec::new();
        let mut shield_hits: Vec<Vec2> = Vec::new();

        for d in &mut self.drums {
            if !d.falling {
                continue;
            }
            d.vel_y += GRAVITY * dt;
            d.pos.y += d.vel_y * dt;

            // A falling barrel strikes the buggy just like a bug does.
            if !d.bonked {
                let overlap = d.pos.x < p_right
                    && d.pos.x + DRUM_W > p_left
                    && d.pos.y < p_bottom
                    && d.pos.y + DRUM_H > p_top;
                if overlap {
                    d.bonked = true;
                    if shielded {
                        shield_hits.push(d.center());
                    } else {
                        life_hits.push(d.center());
                    }
                }
            }

            if d.pos.y >= d.home_y {
                d.pos.y = d.home_y;
                d.vel_y = 0.0;
                d.falling = false;
                d.bonked = false;
            }
        }

        // Shield bounces the barrel off harmlessly; otherwise it costs a life.
        for at in shield_hits {
            self.burst(at, Color::new(0.85, 0.55, 0.15, 1.0), 14, 120.0);
            self.sfx(|a| &a.hit);
        }
        for at in life_hits {
            self.lose_life(at);
        }
    }

    fn update_powerups(&mut self, dt: f32) {
        let py = player_y();
        let px = self.player_x;
        let mut caught: Vec<PowerKind> = Vec::new();
        for p in &mut self.powerups {
            p.vel_y += GRAVITY * 0.25 * dt;
            p.pos.y += p.vel_y * dt;
            p.spin += dt * 3.0;
            if (p.pos.x - px).abs() < PLAYER_W * 0.6
                && p.pos.y > py - 6.0
                && p.pos.y < py + PLAYER_H + 10.0
            {
                caught.push(p.kind);
                p.pos.y = 99999.0; // mark for removal
            }
        }
        for k in caught {
            self.score += 25;
            self.pickup_powerup(k);
            self.sfx(|a| &a.powerup);
        }
        let gy = ground_y();
        self.powerups.retain(|p| p.pos.y < gy + 20.0);
    }

    fn update_particles(&mut self, dt: f32) {
        for p in &mut self.particles {
            p.life -= dt;
            p.pos += p.vel * dt;
            p.vel *= 0.92;
        }
        self.particles.retain(|p| p.life > 0.0);
    }

    // -- Rendering ----------------------------------------------------------
    fn draw(&self) {
        clear_background(Color::new(0.03, 0.03, 0.08, 1.0));
        self.draw_stars();
        self.draw_ground();

        match self.phase {
            Phase::Menu => self.draw_menu(),
            Phase::GameOver => {
                self.draw_world();
                self.draw_game_over();
            }
            _ => {
                self.draw_world();
                self.draw_hud();
                if self.phase == Phase::Paused {
                    self.draw_center_text("PAUSED", 56.0, WHITE);
                }
                if self.banner_timer > 0.0 {
                    let a = (self.banner_timer.min(1.0)).clamp(0.0, 1.0);
                    self.draw_center_text_alpha(&self.banner_text, 64.0, YELLOW, a);
                }
            }
        }

        // Damage flash.
        if self.flash_timer > 0.0 {
            let a = (self.flash_timer / 0.25) * 0.4;
            draw_rectangle(
                0.0,
                0.0,
                screen_width(),
                screen_height(),
                Color::new(1.0, 0.1, 0.1, a),
            );
        }

        // Audio toggle buttons sit on top in every phase.
        self.draw_ui_buttons();
    }

    // --- Audio toggle buttons ----------------------------------------------
    fn draw_ui_buttons(&self) {
        let (sfx_r, music_r) = Self::ui_buttons();
        let m = vec2(mouse_position().0, mouse_position().1);
        self.draw_button_bg(sfx_r, sfx_r.contains(m));
        self.draw_speaker_icon(sfx_r, self.mute_sfx);
        self.draw_button_bg(music_r, music_r.contains(m));
        self.draw_note_icon(music_r, self.mute_music);
    }

    fn draw_button_bg(&self, r: Rect, hovered: bool) {
        let bg = if hovered {
            Color::new(0.26, 0.26, 0.36, 0.95)
        } else {
            Color::new(0.14, 0.14, 0.21, 0.85)
        };
        draw_rectangle(r.x, r.y, r.w, r.h, bg);
        draw_rectangle_lines(r.x, r.y, r.w, r.h, 2.0, Color::new(0.5, 0.5, 0.62, 0.9));
    }

    fn icon_color(muted: bool) -> Color {
        if muted {
            Color::new(0.55, 0.55, 0.6, 1.0)
        } else {
            Color::new(0.92, 0.96, 1.0, 1.0)
        }
    }

    fn muted_slash(r: Rect) {
        draw_line(
            r.x + 7.0,
            r.y + 7.0,
            r.x + r.w - 7.0,
            r.y + r.h - 7.0,
            2.5,
            Color::new(1.0, 0.35, 0.35, 1.0),
        );
    }

    fn draw_speaker_icon(&self, r: Rect, muted: bool) {
        let cx = r.x + r.w * 0.5;
        let cy = r.y + r.h * 0.5;
        let col = Self::icon_color(muted);
        // Magnet box + flaring cone.
        draw_rectangle(cx - 9.0, cy - 3.0, 4.0, 6.0, col);
        draw_triangle(
            vec2(cx - 5.0, cy),
            vec2(cx + 3.0, cy - 8.0),
            vec2(cx + 3.0, cy + 8.0),
            col,
        );
        if muted {
            Self::muted_slash(r);
        } else {
            // Two little sound waves.
            draw_line(cx + 6.0, cy - 4.0, cx + 8.0, cy, 1.6, col);
            draw_line(cx + 8.0, cy, cx + 6.0, cy + 4.0, 1.6, col);
            draw_line(cx + 9.0, cy - 6.0, cx + 11.0, cy, 1.6, col);
            draw_line(cx + 11.0, cy, cx + 9.0, cy + 6.0, 1.6, col);
        }
    }

    fn draw_note_icon(&self, r: Rect, muted: bool) {
        let cx = r.x + r.w * 0.5;
        let cy = r.y + r.h * 0.5;
        let col = Self::icon_color(muted);
        let h1 = vec2(cx - 5.0, cy + 6.0);
        let h2 = vec2(cx + 4.0, cy + 6.0);
        draw_circle(h1.x, h1.y, 3.2, col); // note heads
        draw_circle(h2.x, h2.y, 3.2, col);
        draw_line(h1.x + 2.8, h1.y, h1.x + 2.8, cy - 7.0, 1.8, col); // stems
        draw_line(h2.x + 2.8, h2.y, h2.x + 2.8, cy - 7.0, 1.8, col);
        draw_line(h1.x + 2.8, cy - 7.0, h2.x + 2.8, cy - 7.0, 2.5, col); // beam
        if muted {
            Self::muted_slash(r);
        }
    }

    fn draw_stars(&self) {
        for s in &self.stars {
            let tw = 0.5 + 0.5 * (self.time * s.speed + s.twinkle).sin();
            let y = s.pos.y % screen_height();
            draw_circle(
                s.pos.x % screen_width(),
                y,
                s.size,
                Color::new(1.0, 1.0, 1.0, 0.2 + 0.6 * tw),
            );
        }
    }

    fn draw_ground(&self) {
        let gy = ground_y();
        let w = screen_width();
        draw_rectangle(0.0, gy, w, GROUND_H, Color::new(0.14, 0.13, 0.17, 1.0));
        draw_line(0.0, gy, w, gy, 2.0, Color::new(0.45, 0.43, 0.55, 1.0));
        // Sprinkle a few craters for texture.
        let mut x = 30.0;
        let mut seedy = 1.0;
        while x < w {
            let r = 6.0 + (x * 0.13).sin().abs() * 9.0;
            draw_circle_lines(
                x,
                gy + 26.0 + (x * 0.07 + seedy).cos() * 8.0,
                r,
                1.5,
                Color::new(0.3, 0.28, 0.36, 0.8),
            );
            x += 70.0;
            seedy += 0.7;
        }
    }

    fn draw_world(&self) {
        // Drums.
        for d in &self.drums {
            if !d.alive {
                continue;
            }
            let body = if d.carried {
                Color::new(0.9, 0.7, 0.2, 1.0)
            } else {
                Color::new(0.85, 0.55, 0.15, 1.0)
            };
            draw_rectangle(d.pos.x, d.pos.y, DRUM_W, DRUM_H, body);
            draw_rectangle_lines(
                d.pos.x,
                d.pos.y,
                DRUM_W,
                DRUM_H,
                2.0,
                Color::new(0.5, 0.3, 0.05, 1.0),
            );
            // Hazard band.
            draw_rectangle(
                d.pos.x,
                d.pos.y + DRUM_H * 0.4,
                DRUM_W,
                5.0,
                Color::new(1.0, 0.85, 0.3, 1.0),
            );
        }

        // Power-ups.
        for p in &self.powerups {
            let c = p.kind.color();
            draw_poly(p.pos.x, p.pos.y, 6, 12.0, p.spin.to_degrees(), c);
            draw_poly_lines(p.pos.x, p.pos.y, 6, 12.0, p.spin.to_degrees(), 2.0, WHITE);
            if p.kind == PowerKind::ExtraLife {
                // Draw a heart rather than a letter for the 1-up.
                draw_heart(p.pos.x, p.pos.y - 1.0, 5.0, Color::new(0.15, 0.0, 0.05, 1.0));
            } else {
                let dim = measure_text(p.kind.glyph(), None, 20, 1.0);
                draw_text(
                    p.kind.glyph(),
                    p.pos.x - dim.width * 0.5,
                    p.pos.y + dim.height * 0.5,
                    20.0,
                    BLACK,
                );
            }
        }

        // Bullets.
        for b in &self.bullets {
            draw_rectangle(
                b.pos.x - 2.0,
                b.pos.y - 8.0,
                4.0,
                12.0,
                Color::new(1.0, 0.95, 0.5, 1.0),
            );
        }

        // Bugs.
        for bug in &self.bugs {
            self.draw_bug(bug);
            if bug.boss {
                self.draw_boss_health(bug);
            }
        }

        // Particles.
        for p in &self.particles {
            let a = (p.life / p.max_life).clamp(0.0, 1.0);
            let mut c = p.color;
            c.a = a;
            draw_circle(p.pos.x, p.pos.y, p.size * a, c);
        }

        // Player buggy.
        self.draw_player();
    }

    fn draw_bug(&self, bug: &Bug) {
        let r = bug.radius;
        let x = bug.pos.x;
        let y = bug.pos.y;
        // Wings flap.
        let flap = bug.flap.sin() * r * 0.5;
        let wing = Color::new(bug.color.r * 0.7, bug.color.g * 0.7, bug.color.b * 0.7, 0.9);
        draw_triangle(
            vec2(x, y),
            vec2(x - r * 1.5, y - flap),
            vec2(x - r * 0.6, y + r * 0.5),
            wing,
        );
        draw_triangle(
            vec2(x, y),
            vec2(x + r * 1.5, y - flap),
            vec2(x + r * 0.6, y + r * 0.5),
            wing,
        );
        // Body.
        draw_circle(x, y, r, bug.color);
        draw_circle_lines(x, y, r, 2.0, Color::new(0.0, 0.0, 0.0, 0.5));
        // Menacing horns for the boss.
        if bug.boss {
            draw_triangle(
                vec2(x - r * 0.7, y - r * 0.8),
                vec2(x - r * 0.3, y - r * 0.9),
                vec2(x - r * 0.5, y - r * 1.4),
                bug.color,
            );
            draw_triangle(
                vec2(x + r * 0.7, y - r * 0.8),
                vec2(x + r * 0.3, y - r * 0.9),
                vec2(x + r * 0.5, y - r * 1.4),
                bug.color,
            );
        }
        // Eyes.
        draw_circle(x - r * 0.35, y - r * 0.1, r * 0.22, WHITE);
        draw_circle(x + r * 0.35, y - r * 0.1, r * 0.22, WHITE);
        draw_circle(x - r * 0.35, y - r * 0.1, r * 0.1, BLACK);
        draw_circle(x + r * 0.35, y - r * 0.1, r * 0.1, BLACK);
    }

    // A health bar floating above the boss.
    fn draw_boss_health(&self, bug: &Bug) {
        let w = bug.radius * 2.4;
        let h = 7.0;
        let x = bug.pos.x - w * 0.5;
        let y = bug.pos.y - bug.radius - 18.0;
        let frac = (bug.hp as f32 / bug.max_hp.max(1) as f32).clamp(0.0, 1.0);
        draw_rectangle(x, y, w, h, Color::new(0.1, 0.1, 0.12, 0.85));
        draw_rectangle(x, y, w * frac, h, Color::new(1.0, 0.3, 0.35, 1.0));
        draw_rectangle_lines(x, y, w, h, 1.5, Color::new(0.9, 0.9, 0.95, 0.9));
    }

    fn draw_player(&self) {
        let y = player_y();
        let x = self.player_x;
        let hw = PLAYER_W * 0.5;
        let body = Color::new(0.6, 0.85, 1.0, 1.0);
        // Hull.
        draw_rectangle(x - hw, y + 6.0, PLAYER_W, PLAYER_H - 6.0, body);
        draw_triangle(
            vec2(x - hw, y + 6.0),
            vec2(x + hw, y + 6.0),
            vec2(x, y - 8.0),
            body,
        );
        // Cannon.
        draw_rectangle(x - 3.0, y - 14.0, 6.0, 12.0, Color::new(0.8, 0.95, 1.0, 1.0));
        // Wheels.
        draw_circle(x - hw * 0.55, y + PLAYER_H, 6.0, Color::new(0.3, 0.3, 0.4, 1.0));
        draw_circle(x + hw * 0.55, y + PLAYER_H, 6.0, Color::new(0.3, 0.3, 0.4, 1.0));
        // Shield bubble.
        if self.shield_timer > 0.0 {
            let pulse = 0.4 + 0.3 * (self.time * 8.0).sin();
            draw_circle_lines(
                x,
                y + 4.0,
                PLAYER_W * 0.7,
                2.5,
                Color::new(0.5, 1.0, 0.6, pulse),
            );
        }
    }

    fn draw_hud(&self) {
        draw_text(&format!("SCORE  {}", self.score), 16.0, 30.0, 28.0, WHITE);
        draw_text(
            &format!("BEST  {}", self.high_score),
            16.0,
            56.0,
            22.0,
            Color::new(0.7, 0.7, 0.8, 1.0),
        );
        // Wave (centered top).
        let wt = format!("WAVE {}", self.wave);
        let dim = measure_text(&wt, None, 26, 1.0);
        draw_text(
            &wt,
            screen_width() * 0.5 - dim.width * 0.5,
            30.0,
            26.0,
            Color::new(0.9, 0.9, 0.5, 1.0),
        );

        // Lives (top-right hearts), sitting just below the audio buttons.
        let heart_y = 56.0;
        for i in 0..self.lives.max(0) {
            let cx = screen_width() - 24.0 - i as f32 * 26.0;
            draw_circle(cx - 4.0, heart_y, 5.0, RED);
            draw_circle(cx + 4.0, heart_y, 5.0, RED);
            draw_triangle(
                vec2(cx - 9.0, heart_y + 2.0),
                vec2(cx + 9.0, heart_y + 2.0),
                vec2(cx, heart_y + 12.0),
                RED,
            );
        }

        // Drums remaining.
        draw_text(
            &format!("DRUMS  {}", self.alive_drums()),
            16.0,
            82.0,
            22.0,
            Color::new(0.85, 0.6, 0.2, 1.0),
        );

        // Active weapon / shield indicators.
        if self.weapon != Weapon::Normal {
            let t = format!("{}  {:.0}s", self.weapon.label(), self.weapon_timer.max(0.0));
            draw_text(
                &t,
                16.0,
                screen_height() - 16.0,
                24.0,
                Color::new(0.4, 0.95, 1.0, 1.0),
            );
        }
        if self.shield_timer > 0.0 {
            let t = format!("SHIELD  {:.0}s", self.shield_timer);
            draw_text(
                &t,
                200.0,
                screen_height() - 16.0,
                24.0,
                Color::new(0.5, 1.0, 0.6, 1.0),
            );
        }
    }

    fn draw_menu(&self) {
        self.draw_center_text_y(
            "MOON BUGS",
            76.0,
            Color::new(0.6, 0.9, 1.0, 1.0),
            screen_height() * 0.32,
        );
        self.draw_center_text_y(
            "LUNAR DEFENSE",
            30.0,
            Color::new(0.8, 0.8, 0.9, 1.0),
            screen_height() * 0.32 + 46.0,
        );
        self.draw_center_text_y(
            "Defend your fuel drums from the swooping bugs!",
            24.0,
            WHITE,
            screen_height() * 0.5,
        );
        self.draw_center_text_y(
            "MOVE  </>/A/D    FIRE  Space    PAUSE  P    MUTE  M sfx / N music",
            22.0,
            Color::new(0.7, 0.7, 0.8, 1.0),
            screen_height() * 0.5 + 34.0,
        );
        let blink = (self.time * 3.0).sin() > -0.3;
        if blink {
            self.draw_center_text_y(
                "Press ENTER to launch",
                30.0,
                YELLOW,
                screen_height() * 0.68,
            );
        }
        if self.high_score > 0 {
            self.draw_center_text_y(
                &format!("Best: {}", self.high_score),
                24.0,
                Color::new(0.7, 0.7, 0.8, 1.0),
                screen_height() * 0.78,
            );
        }
    }

    fn draw_game_over(&self) {
        draw_rectangle(
            0.0,
            0.0,
            screen_width(),
            screen_height(),
            Color::new(0.0, 0.0, 0.0, 0.55),
        );
        self.draw_center_text_y(
            "GAME OVER",
            72.0,
            Color::new(1.0, 0.4, 0.4, 1.0),
            screen_height() * 0.34,
        );
        self.draw_center_text_y(
            &format!("Score: {}", self.score),
            36.0,
            WHITE,
            screen_height() * 0.34 + 60.0,
        );
        self.draw_center_text_y(
            &format!("Best: {}", self.high_score),
            28.0,
            Color::new(0.8, 0.8, 0.5, 1.0),
            screen_height() * 0.34 + 100.0,
        );
        self.draw_center_text_y(
            &format!("You reached wave {}", self.wave),
            24.0,
            Color::new(0.7, 0.7, 0.8, 1.0),
            screen_height() * 0.34 + 134.0,
        );
        let blink = (self.time * 3.0).sin() > -0.3;
        if blink {
            self.draw_center_text_y(
                "Press ENTER to play again",
                28.0,
                YELLOW,
                screen_height() * 0.62,
            );
        }
    }

    // -- Text helpers --------------------------------------------------------
    fn draw_center_text(&self, text: &str, size: f32, color: Color) {
        self.draw_center_text_y(text, size, color, screen_height() * 0.5);
    }
    fn draw_center_text_alpha(&self, text: &str, size: f32, mut color: Color, a: f32) {
        color.a = a;
        self.draw_center_text_y(text, size, color, screen_height() * 0.4);
    }
    fn draw_center_text_y(&self, text: &str, size: f32, color: Color, y: f32) {
        let dim = measure_text(text, None, size as u16, 1.0);
        draw_text(text, screen_width() * 0.5 - dim.width * 0.5, y, size, color);
    }
}

fn window_conf() -> Conf {
    Conf {
        window_title: "Moon Bugs — Lunar Defense".to_owned(),
        window_width: 900,
        window_height: 640,
        high_dpi: true,
        // Window / taskbar / dock icon, baked in from procedurally generated
        // raw RGBA buffers (see tools/gen_icon.py). Sizes must match exactly:
        // 16x16, 32x32, 64x64 -> 1024, 4096, 16384 bytes.
        icon: Some(miniquad::conf::Icon {
            small: *include_bytes!("../assets/icon_16.rgba"),
            medium: *include_bytes!("../assets/icon_32.rgba"),
            big: *include_bytes!("../assets/icon_64.rgba"),
        }),
        ..Default::default()
    }
}

#[macroquad::main(window_conf)]
async fn main() {
    srand(macroquad::miniquad::date::now() as u64);
    let mut game = Game::new();
    game.audio = Audio::load().await; // None (silent) if assets are missing
    game.start_music(); // looping background track, runs across all phases

    loop {
        let dt = get_frame_time().min(1.0 / 30.0); // clamp to avoid huge steps

        // --- Global input ---
        if is_key_pressed(KeyCode::Escape) {
            break;
        }
        game.handle_ui_click(); // audio toggle buttons (any phase)
        if is_key_pressed(KeyCode::M) {
            game.mute_sfx = !game.mute_sfx; // keyboard shortcut for the SFX button
        }
        if is_key_pressed(KeyCode::N) {
            game.toggle_music(); // keyboard shortcut for the music button
        }
        match game.phase {
            Phase::Menu | Phase::GameOver => {
                if is_key_pressed(KeyCode::Enter) {
                    game.start();
                }
                game.time += dt; // keep the blink animating
            }
            Phase::Playing => {
                if is_key_pressed(KeyCode::P) {
                    game.phase = Phase::Paused;
                }
                game.update(dt);
            }
            Phase::Paused => {
                game.time += dt;
                if is_key_pressed(KeyCode::P) || is_key_pressed(KeyCode::Enter) {
                    game.phase = Phase::Playing;
                }
            }
        }

        game.draw();
        next_frame().await;
    }
}
